version = 0.1

[default.deploy.parameters]
stack_name = "sam-sentiment"
resolve_s3 = true
s3_prefix = "sam-sentiment"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "S3BucketName=\"kandidat-12345-data\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
